CREATE TABLE `t_user` (
	`user_id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(127) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sns_name` VARCHAR(127) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`password` VARCHAR(63) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`jm_username` VARCHAR(127) NULL DEFAULT '' COMMENT '极光用户名' COLLATE 'utf8_general_ci',
	`jm_password` VARCHAR(63) NULL DEFAULT '' COMMENT '极光密码' COLLATE 'utf8_general_ci',
	`hx_username` VARCHAR(127) NULL DEFAULT '' COMMENT '环信用户名' COLLATE 'utf8_general_ci',
	`hx_password` VARCHAR(63) NULL DEFAULT '' COMMENT '环信密码' COLLATE 'utf8_general_ci',
	`nick_name` VARCHAR(127) NULL DEFAULT '' COMMENT '昵称' COLLATE 'utf8_general_ci',
	`real_name` VARCHAR(63) NULL DEFAULT '' COMMENT '真实姓名 废弃' COLLATE 'utf8_general_ci',
	`gender` INT(1) NULL DEFAULT '3' COMMENT '性别：1男，2女，3保密',
	`age` INT(3) NULL DEFAULT NULL,
	`birthdate` DATE NULL DEFAULT NULL,
	`constellation` VARCHAR(15) NULL DEFAULT '' COMMENT '星座' COLLATE 'utf8_general_ci',
	`user_icon` VARCHAR(255) NULL DEFAULT '' COMMENT '可取消 ' COLLATE 'utf8_general_ci',
	`city` VARCHAR(63) NULL DEFAULT '' COMMENT '城市' COLLATE 'utf8_general_ci',
	`hometown` VARCHAR(63) NULL DEFAULT NULL COMMENT '家乡' COLLATE 'utf8_general_ci',
	`personal_profile` VARCHAR(255) NULL DEFAULT NULL COMMENT '个人简介' COLLATE 'utf8_general_ci',
	`signature` VARCHAR(127) NULL DEFAULT '' COMMENT '签名' COLLATE 'utf8_general_ci',
	`industry` VARCHAR(63) NULL DEFAULT NULL COMMENT '行业' COLLATE 'utf8_general_ci',
	`job` VARCHAR(63) NULL DEFAULT '' COMMENT '职业' COLLATE 'utf8_general_ci',
	`is_approve` INT(1) NULL DEFAULT '0' COMMENT '是否认证，0未认证，1待审核，2认证通过，3未通过',
	`is_teacher` INT(1) NULL DEFAULT '1' COMMENT '是否是导师：2是，1否',
	`marita_status` INT(1) NULL DEFAULT '3' COMMENT '婚姻状况：1未婚，2已婚，3保密4离异',
	`mobile` VARCHAR(15) NULL DEFAULT '' COMMENT '联系电话' COLLATE 'utf8_general_ci',
	`email` VARCHAR(63) NULL DEFAULT '' COMMENT '邮箱' COLLATE 'utf8_general_ci',
	`level` VARCHAR(15) NULL DEFAULT '1' COMMENT '专家；资深专家；大师 等' COLLATE 'utf8_general_ci',
	`integral` INT(11) NULL DEFAULT '0' COMMENT '积分',
	`laugitude` DOUBLE(15,6) NULL DEFAULT '0.000000' COMMENT '经度',
	`latitude` DOUBLE(15,6) NULL DEFAULT '0.000000' COMMENT '纬度',
	`login_status` INT(1) NULL DEFAULT '2' COMMENT '登录状态，1表示登录中，2标志未登录',
	`login_date` DATETIME NULL DEFAULT NULL,
	`registration_id` VARCHAR(63) NULL DEFAULT NULL COMMENT '登录设备id' COLLATE 'utf8_general_ci',
	`activated` INT(1) NULL DEFAULT '0' COMMENT '登录状态标记，',
	`deleted` INT(1) NULL DEFAULT '1' COMMENT '账号状态：1正常，2封号，3暂停使用',
	`created_date` DATETIME NULL DEFAULT NULL,
	`updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`politcs` VARCHAR(63) NULL DEFAULT '' COMMENT '政治面貌' COLLATE 'utf8_general_ci',
	`religions` VARCHAR(63) NULL DEFAULT '' COMMENT '宗教信仰' COLLATE 'utf8_general_ci',
	`educationSeq` INT(3) NULL DEFAULT '0' COMMENT '当前教育信息序号',
	`careerSeq` INT(3) NULL DEFAULT '0' COMMENT '当前职业信息序号',
	`isStudent` INT(1) NULL DEFAULT NULL COMMENT '当前是否在校生',
	`education` VARCHAR(31) NULL DEFAULT NULL COMMENT '最高学历' COLLATE 'utf8_general_ci',
	`profession` VARCHAR(63) NULL DEFAULT NULL COMMENT '专业' COLLATE 'utf8_general_ci',
	`baseAuth` INT(1) NULL DEFAULT NULL COMMENT '基本信息(性别年龄)是否认证 0-未认证 1-已认证',
	`eduAuth` INT(1) NULL DEFAULT NULL COMMENT '最高学历信息是否已认证 0-未认证 1-已认证',
	`careerAuth` INT(1) NULL DEFAULT NULL COMMENT '职业信息是否已认证 0-未认证 1-已认证',
	`eduInfo` VARCHAR(127) NULL DEFAULT NULL COMMENT '展示的最高学历信息' COLLATE 'utf8_general_ci',
	`careerInfo` VARCHAR(127) NULL DEFAULT NULL COMMENT '展示的职业信息' COLLATE 'utf8_general_ci',
	`currentInfo` VARCHAR(127) NULL DEFAULT NULL COMMENT '展示的当前信息' COLLATE 'utf8_general_ci',
	`currentAuth` INT(1) NULL DEFAULT NULL COMMENT '当前信息是否已认证 0-未认证 1-已认证',
	`school` VARCHAR(255) NULL DEFAULT NULL COMMENT '学校' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`user_id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT
AUTO_INCREMENT=411
;
